#Playbook for Insatalling and Configuring Nginx
- name: Play for Installing Nginx
  tags: Nginx
  hosts: web
  tasks:
    - name: Perform apt update
      shell: apt update
    
    - name: Install Nginx
      shell: apt install nginx -y

    - name: Start Nginx Service
      shell: service nginx start

#Playbook for Insatalling and Configuring Nginx
- name: Play for Creating Testuser 1 & 2
  tags: Testuser
  hosts: web:app:!db
  tasks:
    - name: Creating Test User 1
      user:
        name: Testuser1
        state: present
    - name: Creating Test User 2
      user:
        name: Testuser2
        state: present

#Playbook for Creating Devuser 1 to 5
- name: Play for Creating Devuser 1 to 5
  tags: Devuser
  hosts: web:app:db
  tasks:
    - name: Creating Dev User 1 to 5
      user:
        name: "{{ item }}"
        state: present
      with_items:
          - Devuser1
          - Devuser2
          - Devuser3
          - Devuser4
          - Devuser5

#Install AWS CLI on App Servers
- name: Install AWS CLI on App Servers
  tags: AWSCLI
  hosts: app
  tasks:
    - name: Install unzip on app servers
      shell: apt install unzip -y

    - name: Download AWS CLI
      get_url:
          url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
          dest: ./awscliv2.zip

    - name: Unzip file & Install
      shell: unzip awscliv2.zip && ./aws/install
