---
- name: Play for Installing Apache HTTP Server
  hosts: web:app
  become: true
  tasks:
   - name: Install Apache HTTP Server
     apt: #use yum for RHEL & centos and apt for ubuntu
      name: apache2
      state: latest
   - name: Copy index.html
     copy:
     src: index.html
     dest: /var/www/html/index.html
   - name: Start HTTP Server
     service:
      name: apache2
      state: started
      enabled: yes
...