---
- name: Play for Installing Apache HTTP Server
  hosts: web
  become: true
  vars :
   env: Dev  #This will act as default, i.e is if we had not passed any 
             #extra-vars during running of playbook then by default it will
             #take Dev as Env.

  vars_files:
    - "{{env}}_vars.yaml"
    
  tasks:
   - name: Install Apache HTTP Server
     apt: #use yum for RHEL & centos and apt for ubuntu
      name: apache2
      state: latest
   - name: Copy index.html
     template:
      src: index.html
      dest: /var/www/html/index.html
     notify:
     - Re-start the Apache2 Server
     
  handlers:
   - name: Re-start the Apache2 Server
     service:
      name: apache2
      state: started
      enabled: yes
...